/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the LabelsNodePoolBrief type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelsNodePoolBrief{}

// LabelsNodePoolBrief struct for LabelsNodePoolBrief
type LabelsNodePoolBrief struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewLabelsNodePoolBrief instantiates a new LabelsNodePoolBrief object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelsNodePoolBrief() *LabelsNodePoolBrief {
	this := LabelsNodePoolBrief{}
	return &this
}

// NewLabelsNodePoolBriefWithDefaults instantiates a new LabelsNodePoolBrief object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelsNodePoolBriefWithDefaults() *LabelsNodePoolBrief {
	this := LabelsNodePoolBrief{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LabelsNodePoolBrief) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelsNodePoolBrief) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LabelsNodePoolBrief) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LabelsNodePoolBrief) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LabelsNodePoolBrief) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelsNodePoolBrief) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LabelsNodePoolBrief) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LabelsNodePoolBrief) SetName(v string) {
	o.Name = &v
}

func (o LabelsNodePoolBrief) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelsNodePoolBrief) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableLabelsNodePoolBrief struct {
	value *LabelsNodePoolBrief
	isSet bool
}

func (v NullableLabelsNodePoolBrief) Get() *LabelsNodePoolBrief {
	return v.value
}

func (v *NullableLabelsNodePoolBrief) Set(val *LabelsNodePoolBrief) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelsNodePoolBrief) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelsNodePoolBrief) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelsNodePoolBrief(val *LabelsNodePoolBrief) *NullableLabelsNodePoolBrief {
	return &NullableLabelsNodePoolBrief{value: val, isSet: true}
}

func (v NullableLabelsNodePoolBrief) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelsNodePoolBrief) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
