/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the NodepoolsAnnotationBrief type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodepoolsAnnotationBrief{}

// NodepoolsAnnotationBrief struct for NodepoolsAnnotationBrief
type NodepoolsAnnotationBrief struct {
	Id    *string `json:"id,omitempty"`
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewNodepoolsAnnotationBrief instantiates a new NodepoolsAnnotationBrief object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodepoolsAnnotationBrief() *NodepoolsAnnotationBrief {
	this := NodepoolsAnnotationBrief{}
	return &this
}

// NewNodepoolsAnnotationBriefWithDefaults instantiates a new NodepoolsAnnotationBrief object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodepoolsAnnotationBriefWithDefaults() *NodepoolsAnnotationBrief {
	this := NodepoolsAnnotationBrief{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NodepoolsAnnotationBrief) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodepoolsAnnotationBrief) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NodepoolsAnnotationBrief) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NodepoolsAnnotationBrief) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *NodepoolsAnnotationBrief) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodepoolsAnnotationBrief) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *NodepoolsAnnotationBrief) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *NodepoolsAnnotationBrief) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *NodepoolsAnnotationBrief) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodepoolsAnnotationBrief) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *NodepoolsAnnotationBrief) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *NodepoolsAnnotationBrief) SetValue(v string) {
	o.Value = &v
}

func (o NodepoolsAnnotationBrief) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodepoolsAnnotationBrief) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableNodepoolsAnnotationBrief struct {
	value *NodepoolsAnnotationBrief
	isSet bool
}

func (v NullableNodepoolsAnnotationBrief) Get() *NodepoolsAnnotationBrief {
	return v.value
}

func (v *NullableNodepoolsAnnotationBrief) Set(val *NodepoolsAnnotationBrief) {
	v.value = val
	v.isSet = true
}

func (v NullableNodepoolsAnnotationBrief) IsSet() bool {
	return v.isSet
}

func (v *NullableNodepoolsAnnotationBrief) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodepoolsAnnotationBrief(val *NodepoolsAnnotationBrief) *NullableNodepoolsAnnotationBrief {
	return &NullableNodepoolsAnnotationBrief{value: val, isSet: true}
}

func (v NullableNodepoolsAnnotationBrief) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodepoolsAnnotationBrief) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
