/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the LabelsLabelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelsLabelResponse{}

// LabelsLabelResponse struct for LabelsLabelResponse
type LabelsLabelResponse struct {
	Id         *string               `json:"id,omitempty"`
	Key        *string               `json:"key,omitempty"`
	NodeGroups []LabelsNodePoolBrief `json:"node_groups,omitempty"`
	Value      *string               `json:"value,omitempty"`
}

// NewLabelsLabelResponse instantiates a new LabelsLabelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelsLabelResponse() *LabelsLabelResponse {
	this := LabelsLabelResponse{}
	return &this
}

// NewLabelsLabelResponseWithDefaults instantiates a new LabelsLabelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelsLabelResponseWithDefaults() *LabelsLabelResponse {
	this := LabelsLabelResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LabelsLabelResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelsLabelResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LabelsLabelResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LabelsLabelResponse) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *LabelsLabelResponse) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelsLabelResponse) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *LabelsLabelResponse) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *LabelsLabelResponse) SetKey(v string) {
	o.Key = &v
}

// GetNodeGroups returns the NodeGroups field value if set, zero value otherwise.
func (o *LabelsLabelResponse) GetNodeGroups() []LabelsNodePoolBrief {
	if o == nil || IsNil(o.NodeGroups) {
		var ret []LabelsNodePoolBrief
		return ret
	}
	return o.NodeGroups
}

// GetNodeGroupsOk returns a tuple with the NodeGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelsLabelResponse) GetNodeGroupsOk() ([]LabelsNodePoolBrief, bool) {
	if o == nil || IsNil(o.NodeGroups) {
		return nil, false
	}
	return o.NodeGroups, true
}

// HasNodeGroups returns a boolean if a field has been set.
func (o *LabelsLabelResponse) HasNodeGroups() bool {
	if o != nil && !IsNil(o.NodeGroups) {
		return true
	}

	return false
}

// SetNodeGroups gets a reference to the given []LabelsNodePoolBrief and assigns it to the NodeGroups field.
func (o *LabelsLabelResponse) SetNodeGroups(v []LabelsNodePoolBrief) {
	o.NodeGroups = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *LabelsLabelResponse) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelsLabelResponse) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *LabelsLabelResponse) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *LabelsLabelResponse) SetValue(v string) {
	o.Value = &v
}

func (o LabelsLabelResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelsLabelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.NodeGroups) {
		toSerialize["node_groups"] = o.NodeGroups
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableLabelsLabelResponse struct {
	value *LabelsLabelResponse
	isSet bool
}

func (v NullableLabelsLabelResponse) Get() *LabelsLabelResponse {
	return v.value
}

func (v *NullableLabelsLabelResponse) Set(val *LabelsLabelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelsLabelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelsLabelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelsLabelResponse(val *LabelsLabelResponse) *NullableLabelsLabelResponse {
	return &NullableLabelsLabelResponse{value: val, isSet: true}
}

func (v NullableLabelsLabelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelsLabelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
