/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the ClustersClusterResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClustersClusterResponse{}

// ClustersClusterResponse struct for ClustersClusterResponse
type ClustersClusterResponse struct {
	BastionServer       *ClustersServerBrief    `json:"bastion_server,omitempty"`
	ClusterLoadBalancer *string                 `json:"cluster_load_balancer,omitempty"`
	ControlLoadBalancer *string                 `json:"control_load_balancer,omitempty"`
	Id                  *string                 `json:"id,omitempty"`
	Name                *string                 `json:"name,omitempty"`
	NodePools           []ClustersNodePoolBrief `json:"node_pools,omitempty"`
	Provider            *string                 `json:"provider,omitempty"`
	Region              *string                 `json:"region,omitempty"`
	Status              *string                 `json:"status,omitempty"`
}

// NewClustersClusterResponse instantiates a new ClustersClusterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClustersClusterResponse() *ClustersClusterResponse {
	this := ClustersClusterResponse{}
	return &this
}

// NewClustersClusterResponseWithDefaults instantiates a new ClustersClusterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClustersClusterResponseWithDefaults() *ClustersClusterResponse {
	this := ClustersClusterResponse{}
	return &this
}

// GetBastionServer returns the BastionServer field value if set, zero value otherwise.
func (o *ClustersClusterResponse) GetBastionServer() ClustersServerBrief {
	if o == nil || IsNil(o.BastionServer) {
		var ret ClustersServerBrief
		return ret
	}
	return *o.BastionServer
}

// GetBastionServerOk returns a tuple with the BastionServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersClusterResponse) GetBastionServerOk() (*ClustersServerBrief, bool) {
	if o == nil || IsNil(o.BastionServer) {
		return nil, false
	}
	return o.BastionServer, true
}

// HasBastionServer returns a boolean if a field has been set.
func (o *ClustersClusterResponse) HasBastionServer() bool {
	if o != nil && !IsNil(o.BastionServer) {
		return true
	}

	return false
}

// SetBastionServer gets a reference to the given ClustersServerBrief and assigns it to the BastionServer field.
func (o *ClustersClusterResponse) SetBastionServer(v ClustersServerBrief) {
	o.BastionServer = &v
}

// GetClusterLoadBalancer returns the ClusterLoadBalancer field value if set, zero value otherwise.
func (o *ClustersClusterResponse) GetClusterLoadBalancer() string {
	if o == nil || IsNil(o.ClusterLoadBalancer) {
		var ret string
		return ret
	}
	return *o.ClusterLoadBalancer
}

// GetClusterLoadBalancerOk returns a tuple with the ClusterLoadBalancer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersClusterResponse) GetClusterLoadBalancerOk() (*string, bool) {
	if o == nil || IsNil(o.ClusterLoadBalancer) {
		return nil, false
	}
	return o.ClusterLoadBalancer, true
}

// HasClusterLoadBalancer returns a boolean if a field has been set.
func (o *ClustersClusterResponse) HasClusterLoadBalancer() bool {
	if o != nil && !IsNil(o.ClusterLoadBalancer) {
		return true
	}

	return false
}

// SetClusterLoadBalancer gets a reference to the given string and assigns it to the ClusterLoadBalancer field.
func (o *ClustersClusterResponse) SetClusterLoadBalancer(v string) {
	o.ClusterLoadBalancer = &v
}

// GetControlLoadBalancer returns the ControlLoadBalancer field value if set, zero value otherwise.
func (o *ClustersClusterResponse) GetControlLoadBalancer() string {
	if o == nil || IsNil(o.ControlLoadBalancer) {
		var ret string
		return ret
	}
	return *o.ControlLoadBalancer
}

// GetControlLoadBalancerOk returns a tuple with the ControlLoadBalancer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersClusterResponse) GetControlLoadBalancerOk() (*string, bool) {
	if o == nil || IsNil(o.ControlLoadBalancer) {
		return nil, false
	}
	return o.ControlLoadBalancer, true
}

// HasControlLoadBalancer returns a boolean if a field has been set.
func (o *ClustersClusterResponse) HasControlLoadBalancer() bool {
	if o != nil && !IsNil(o.ControlLoadBalancer) {
		return true
	}

	return false
}

// SetControlLoadBalancer gets a reference to the given string and assigns it to the ControlLoadBalancer field.
func (o *ClustersClusterResponse) SetControlLoadBalancer(v string) {
	o.ControlLoadBalancer = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ClustersClusterResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersClusterResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ClustersClusterResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ClustersClusterResponse) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClustersClusterResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersClusterResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClustersClusterResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClustersClusterResponse) SetName(v string) {
	o.Name = &v
}

// GetNodePools returns the NodePools field value if set, zero value otherwise.
func (o *ClustersClusterResponse) GetNodePools() []ClustersNodePoolBrief {
	if o == nil || IsNil(o.NodePools) {
		var ret []ClustersNodePoolBrief
		return ret
	}
	return o.NodePools
}

// GetNodePoolsOk returns a tuple with the NodePools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersClusterResponse) GetNodePoolsOk() ([]ClustersNodePoolBrief, bool) {
	if o == nil || IsNil(o.NodePools) {
		return nil, false
	}
	return o.NodePools, true
}

// HasNodePools returns a boolean if a field has been set.
func (o *ClustersClusterResponse) HasNodePools() bool {
	if o != nil && !IsNil(o.NodePools) {
		return true
	}

	return false
}

// SetNodePools gets a reference to the given []ClustersNodePoolBrief and assigns it to the NodePools field.
func (o *ClustersClusterResponse) SetNodePools(v []ClustersNodePoolBrief) {
	o.NodePools = v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *ClustersClusterResponse) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersClusterResponse) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *ClustersClusterResponse) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *ClustersClusterResponse) SetProvider(v string) {
	o.Provider = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *ClustersClusterResponse) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersClusterResponse) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *ClustersClusterResponse) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *ClustersClusterResponse) SetRegion(v string) {
	o.Region = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ClustersClusterResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersClusterResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ClustersClusterResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ClustersClusterResponse) SetStatus(v string) {
	o.Status = &v
}

func (o ClustersClusterResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClustersClusterResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BastionServer) {
		toSerialize["bastion_server"] = o.BastionServer
	}
	if !IsNil(o.ClusterLoadBalancer) {
		toSerialize["cluster_load_balancer"] = o.ClusterLoadBalancer
	}
	if !IsNil(o.ControlLoadBalancer) {
		toSerialize["control_load_balancer"] = o.ControlLoadBalancer
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NodePools) {
		toSerialize["node_pools"] = o.NodePools
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableClustersClusterResponse struct {
	value *ClustersClusterResponse
	isSet bool
}

func (v NullableClustersClusterResponse) Get() *ClustersClusterResponse {
	return v.value
}

func (v *NullableClustersClusterResponse) Set(val *ClustersClusterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClustersClusterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClustersClusterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClustersClusterResponse(val *ClustersClusterResponse) *NullableClustersClusterResponse {
	return &NullableClustersClusterResponse{value: val, isSet: true}
}

func (v NullableClustersClusterResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClustersClusterResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
