/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the JobsQueueRollup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobsQueueRollup{}

// JobsQueueRollup struct for JobsQueueRollup
type JobsQueueRollup struct {
	AvgDurationSecs *float64 `json:"avg_duration_secs,omitempty"`
	Failed24h       *int32   `json:"failed_24h,omitempty"`
	QueueName       *string  `json:"queue_name,omitempty"`
	QueuedDue       *int32   `json:"queued_due,omitempty"`
	QueuedFuture    *int32   `json:"queued_future,omitempty"`
	Running         *int32   `json:"running,omitempty"`
	Success24h      *int32   `json:"success_24h,omitempty"`
}

// NewJobsQueueRollup instantiates a new JobsQueueRollup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobsQueueRollup() *JobsQueueRollup {
	this := JobsQueueRollup{}
	return &this
}

// NewJobsQueueRollupWithDefaults instantiates a new JobsQueueRollup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobsQueueRollupWithDefaults() *JobsQueueRollup {
	this := JobsQueueRollup{}
	return &this
}

// GetAvgDurationSecs returns the AvgDurationSecs field value if set, zero value otherwise.
func (o *JobsQueueRollup) GetAvgDurationSecs() float64 {
	if o == nil || IsNil(o.AvgDurationSecs) {
		var ret float64
		return ret
	}
	return *o.AvgDurationSecs
}

// GetAvgDurationSecsOk returns a tuple with the AvgDurationSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsQueueRollup) GetAvgDurationSecsOk() (*float64, bool) {
	if o == nil || IsNil(o.AvgDurationSecs) {
		return nil, false
	}
	return o.AvgDurationSecs, true
}

// HasAvgDurationSecs returns a boolean if a field has been set.
func (o *JobsQueueRollup) HasAvgDurationSecs() bool {
	if o != nil && !IsNil(o.AvgDurationSecs) {
		return true
	}

	return false
}

// SetAvgDurationSecs gets a reference to the given float64 and assigns it to the AvgDurationSecs field.
func (o *JobsQueueRollup) SetAvgDurationSecs(v float64) {
	o.AvgDurationSecs = &v
}

// GetFailed24h returns the Failed24h field value if set, zero value otherwise.
func (o *JobsQueueRollup) GetFailed24h() int32 {
	if o == nil || IsNil(o.Failed24h) {
		var ret int32
		return ret
	}
	return *o.Failed24h
}

// GetFailed24hOk returns a tuple with the Failed24h field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsQueueRollup) GetFailed24hOk() (*int32, bool) {
	if o == nil || IsNil(o.Failed24h) {
		return nil, false
	}
	return o.Failed24h, true
}

// HasFailed24h returns a boolean if a field has been set.
func (o *JobsQueueRollup) HasFailed24h() bool {
	if o != nil && !IsNil(o.Failed24h) {
		return true
	}

	return false
}

// SetFailed24h gets a reference to the given int32 and assigns it to the Failed24h field.
func (o *JobsQueueRollup) SetFailed24h(v int32) {
	o.Failed24h = &v
}

// GetQueueName returns the QueueName field value if set, zero value otherwise.
func (o *JobsQueueRollup) GetQueueName() string {
	if o == nil || IsNil(o.QueueName) {
		var ret string
		return ret
	}
	return *o.QueueName
}

// GetQueueNameOk returns a tuple with the QueueName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsQueueRollup) GetQueueNameOk() (*string, bool) {
	if o == nil || IsNil(o.QueueName) {
		return nil, false
	}
	return o.QueueName, true
}

// HasQueueName returns a boolean if a field has been set.
func (o *JobsQueueRollup) HasQueueName() bool {
	if o != nil && !IsNil(o.QueueName) {
		return true
	}

	return false
}

// SetQueueName gets a reference to the given string and assigns it to the QueueName field.
func (o *JobsQueueRollup) SetQueueName(v string) {
	o.QueueName = &v
}

// GetQueuedDue returns the QueuedDue field value if set, zero value otherwise.
func (o *JobsQueueRollup) GetQueuedDue() int32 {
	if o == nil || IsNil(o.QueuedDue) {
		var ret int32
		return ret
	}
	return *o.QueuedDue
}

// GetQueuedDueOk returns a tuple with the QueuedDue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsQueueRollup) GetQueuedDueOk() (*int32, bool) {
	if o == nil || IsNil(o.QueuedDue) {
		return nil, false
	}
	return o.QueuedDue, true
}

// HasQueuedDue returns a boolean if a field has been set.
func (o *JobsQueueRollup) HasQueuedDue() bool {
	if o != nil && !IsNil(o.QueuedDue) {
		return true
	}

	return false
}

// SetQueuedDue gets a reference to the given int32 and assigns it to the QueuedDue field.
func (o *JobsQueueRollup) SetQueuedDue(v int32) {
	o.QueuedDue = &v
}

// GetQueuedFuture returns the QueuedFuture field value if set, zero value otherwise.
func (o *JobsQueueRollup) GetQueuedFuture() int32 {
	if o == nil || IsNil(o.QueuedFuture) {
		var ret int32
		return ret
	}
	return *o.QueuedFuture
}

// GetQueuedFutureOk returns a tuple with the QueuedFuture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsQueueRollup) GetQueuedFutureOk() (*int32, bool) {
	if o == nil || IsNil(o.QueuedFuture) {
		return nil, false
	}
	return o.QueuedFuture, true
}

// HasQueuedFuture returns a boolean if a field has been set.
func (o *JobsQueueRollup) HasQueuedFuture() bool {
	if o != nil && !IsNil(o.QueuedFuture) {
		return true
	}

	return false
}

// SetQueuedFuture gets a reference to the given int32 and assigns it to the QueuedFuture field.
func (o *JobsQueueRollup) SetQueuedFuture(v int32) {
	o.QueuedFuture = &v
}

// GetRunning returns the Running field value if set, zero value otherwise.
func (o *JobsQueueRollup) GetRunning() int32 {
	if o == nil || IsNil(o.Running) {
		var ret int32
		return ret
	}
	return *o.Running
}

// GetRunningOk returns a tuple with the Running field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsQueueRollup) GetRunningOk() (*int32, bool) {
	if o == nil || IsNil(o.Running) {
		return nil, false
	}
	return o.Running, true
}

// HasRunning returns a boolean if a field has been set.
func (o *JobsQueueRollup) HasRunning() bool {
	if o != nil && !IsNil(o.Running) {
		return true
	}

	return false
}

// SetRunning gets a reference to the given int32 and assigns it to the Running field.
func (o *JobsQueueRollup) SetRunning(v int32) {
	o.Running = &v
}

// GetSuccess24h returns the Success24h field value if set, zero value otherwise.
func (o *JobsQueueRollup) GetSuccess24h() int32 {
	if o == nil || IsNil(o.Success24h) {
		var ret int32
		return ret
	}
	return *o.Success24h
}

// GetSuccess24hOk returns a tuple with the Success24h field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsQueueRollup) GetSuccess24hOk() (*int32, bool) {
	if o == nil || IsNil(o.Success24h) {
		return nil, false
	}
	return o.Success24h, true
}

// HasSuccess24h returns a boolean if a field has been set.
func (o *JobsQueueRollup) HasSuccess24h() bool {
	if o != nil && !IsNil(o.Success24h) {
		return true
	}

	return false
}

// SetSuccess24h gets a reference to the given int32 and assigns it to the Success24h field.
func (o *JobsQueueRollup) SetSuccess24h(v int32) {
	o.Success24h = &v
}

func (o JobsQueueRollup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobsQueueRollup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvgDurationSecs) {
		toSerialize["avg_duration_secs"] = o.AvgDurationSecs
	}
	if !IsNil(o.Failed24h) {
		toSerialize["failed_24h"] = o.Failed24h
	}
	if !IsNil(o.QueueName) {
		toSerialize["queue_name"] = o.QueueName
	}
	if !IsNil(o.QueuedDue) {
		toSerialize["queued_due"] = o.QueuedDue
	}
	if !IsNil(o.QueuedFuture) {
		toSerialize["queued_future"] = o.QueuedFuture
	}
	if !IsNil(o.Running) {
		toSerialize["running"] = o.Running
	}
	if !IsNil(o.Success24h) {
		toSerialize["success_24h"] = o.Success24h
	}
	return toSerialize, nil
}

type NullableJobsQueueRollup struct {
	value *JobsQueueRollup
	isSet bool
}

func (v NullableJobsQueueRollup) Get() *JobsQueueRollup {
	return v.value
}

func (v *NullableJobsQueueRollup) Set(val *JobsQueueRollup) {
	v.value = val
	v.isSet = true
}

func (v NullableJobsQueueRollup) IsSet() bool {
	return v.isSet
}

func (v *NullableJobsQueueRollup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobsQueueRollup(val *JobsQueueRollup) *NullableJobsQueueRollup {
	return &NullableJobsQueueRollup{value: val, isSet: true}
}

func (v NullableJobsQueueRollup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobsQueueRollup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
