/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the JobsEnqueueReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobsEnqueueReq{}

// JobsEnqueueReq struct for JobsEnqueueReq
type JobsEnqueueReq struct {
	Args       map[string]interface{} `json:"args,omitempty"`
	MaxRetries *int32                 `json:"max_retries,omitempty"`
	Queue      *string                `json:"queue,omitempty"`
	ScheduleAt *string                `json:"schedule_at,omitempty"`
}

// NewJobsEnqueueReq instantiates a new JobsEnqueueReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobsEnqueueReq() *JobsEnqueueReq {
	this := JobsEnqueueReq{}
	return &this
}

// NewJobsEnqueueReqWithDefaults instantiates a new JobsEnqueueReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobsEnqueueReqWithDefaults() *JobsEnqueueReq {
	this := JobsEnqueueReq{}
	return &this
}

// GetArgs returns the Args field value if set, zero value otherwise.
func (o *JobsEnqueueReq) GetArgs() map[string]interface{} {
	if o == nil || IsNil(o.Args) {
		var ret map[string]interface{}
		return ret
	}
	return o.Args
}

// GetArgsOk returns a tuple with the Args field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsEnqueueReq) GetArgsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Args) {
		return map[string]interface{}{}, false
	}
	return o.Args, true
}

// HasArgs returns a boolean if a field has been set.
func (o *JobsEnqueueReq) HasArgs() bool {
	if o != nil && !IsNil(o.Args) {
		return true
	}

	return false
}

// SetArgs gets a reference to the given map[string]interface{} and assigns it to the Args field.
func (o *JobsEnqueueReq) SetArgs(v map[string]interface{}) {
	o.Args = v
}

// GetMaxRetries returns the MaxRetries field value if set, zero value otherwise.
func (o *JobsEnqueueReq) GetMaxRetries() int32 {
	if o == nil || IsNil(o.MaxRetries) {
		var ret int32
		return ret
	}
	return *o.MaxRetries
}

// GetMaxRetriesOk returns a tuple with the MaxRetries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsEnqueueReq) GetMaxRetriesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxRetries) {
		return nil, false
	}
	return o.MaxRetries, true
}

// HasMaxRetries returns a boolean if a field has been set.
func (o *JobsEnqueueReq) HasMaxRetries() bool {
	if o != nil && !IsNil(o.MaxRetries) {
		return true
	}

	return false
}

// SetMaxRetries gets a reference to the given int32 and assigns it to the MaxRetries field.
func (o *JobsEnqueueReq) SetMaxRetries(v int32) {
	o.MaxRetries = &v
}

// GetQueue returns the Queue field value if set, zero value otherwise.
func (o *JobsEnqueueReq) GetQueue() string {
	if o == nil || IsNil(o.Queue) {
		var ret string
		return ret
	}
	return *o.Queue
}

// GetQueueOk returns a tuple with the Queue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsEnqueueReq) GetQueueOk() (*string, bool) {
	if o == nil || IsNil(o.Queue) {
		return nil, false
	}
	return o.Queue, true
}

// HasQueue returns a boolean if a field has been set.
func (o *JobsEnqueueReq) HasQueue() bool {
	if o != nil && !IsNil(o.Queue) {
		return true
	}

	return false
}

// SetQueue gets a reference to the given string and assigns it to the Queue field.
func (o *JobsEnqueueReq) SetQueue(v string) {
	o.Queue = &v
}

// GetScheduleAt returns the ScheduleAt field value if set, zero value otherwise.
func (o *JobsEnqueueReq) GetScheduleAt() string {
	if o == nil || IsNil(o.ScheduleAt) {
		var ret string
		return ret
	}
	return *o.ScheduleAt
}

// GetScheduleAtOk returns a tuple with the ScheduleAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsEnqueueReq) GetScheduleAtOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduleAt) {
		return nil, false
	}
	return o.ScheduleAt, true
}

// HasScheduleAt returns a boolean if a field has been set.
func (o *JobsEnqueueReq) HasScheduleAt() bool {
	if o != nil && !IsNil(o.ScheduleAt) {
		return true
	}

	return false
}

// SetScheduleAt gets a reference to the given string and assigns it to the ScheduleAt field.
func (o *JobsEnqueueReq) SetScheduleAt(v string) {
	o.ScheduleAt = &v
}

func (o JobsEnqueueReq) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobsEnqueueReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Args) {
		toSerialize["args"] = o.Args
	}
	if !IsNil(o.MaxRetries) {
		toSerialize["max_retries"] = o.MaxRetries
	}
	if !IsNil(o.Queue) {
		toSerialize["queue"] = o.Queue
	}
	if !IsNil(o.ScheduleAt) {
		toSerialize["schedule_at"] = o.ScheduleAt
	}
	return toSerialize, nil
}

type NullableJobsEnqueueReq struct {
	value *JobsEnqueueReq
	isSet bool
}

func (v NullableJobsEnqueueReq) Get() *JobsEnqueueReq {
	return v.value
}

func (v *NullableJobsEnqueueReq) Set(val *JobsEnqueueReq) {
	v.value = val
	v.isSet = true
}

func (v NullableJobsEnqueueReq) IsSet() bool {
	return v.isSet
}

func (v *NullableJobsEnqueueReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobsEnqueueReq(val *JobsEnqueueReq) *NullableJobsEnqueueReq {
	return &NullableJobsEnqueueReq{value: val, isSet: true}
}

func (v NullableJobsEnqueueReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobsEnqueueReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
