/*
AutoGlue API

API for managing K3s clusters across cloud providers

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package autoglue

import (
	"encoding/json"
)

// checks if the AuthnLoginInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthnLoginInput{}

// AuthnLoginInput struct for AuthnLoginInput
type AuthnLoginInput struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewAuthnLoginInput instantiates a new AuthnLoginInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthnLoginInput() *AuthnLoginInput {
	this := AuthnLoginInput{}
	return &this
}

// NewAuthnLoginInputWithDefaults instantiates a new AuthnLoginInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthnLoginInputWithDefaults() *AuthnLoginInput {
	this := AuthnLoginInput{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *AuthnLoginInput) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthnLoginInput) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *AuthnLoginInput) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *AuthnLoginInput) SetEmail(v string) {
	o.Email = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *AuthnLoginInput) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthnLoginInput) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *AuthnLoginInput) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *AuthnLoginInput) SetPassword(v string) {
	o.Password = &v
}

func (o AuthnLoginInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthnLoginInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableAuthnLoginInput struct {
	value *AuthnLoginInput
	isSet bool
}

func (v NullableAuthnLoginInput) Get() *AuthnLoginInput {
	return v.value
}

func (v *NullableAuthnLoginInput) Set(val *AuthnLoginInput) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthnLoginInput) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthnLoginInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthnLoginInput(val *AuthnLoginInput) *NullableAuthnLoginInput {
	return &NullableAuthnLoginInput{value: val, isSet: true}
}

func (v NullableAuthnLoginInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthnLoginInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
