/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AuthnRegisterInput
 */
export interface AuthnRegisterInput {
  /**
   *
   * @type {string}
   * @memberof AuthnRegisterInput
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof AuthnRegisterInput
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof AuthnRegisterInput
   */
  password?: string;
}

/**
 * Check if a given object implements the AuthnRegisterInput interface.
 */
export function instanceOfAuthnRegisterInput(
  value: object,
): value is AuthnRegisterInput {
  return true;
}

export function AuthnRegisterInputFromJSON(json: any): AuthnRegisterInput {
  return AuthnRegisterInputFromJSONTyped(json, false);
}

export function AuthnRegisterInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AuthnRegisterInput {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"] == null ? undefined : json["email"],
    name: json["name"] == null ? undefined : json["name"],
    password: json["password"] == null ? undefined : json["password"],
  };
}

export function AuthnRegisterInputToJSON(json: any): AuthnRegisterInput {
  return AuthnRegisterInputToJSONTyped(json, false);
}

export function AuthnRegisterInputToJSONTyped(
  value?: AuthnRegisterInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
    name: value["name"],
    password: value["password"],
  };
}
