/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AuthnUserOut
 */
export interface AuthnUserOut {
  /**
   *
   * @type {object}
   * @memberof AuthnUserOut
   */
  created_at?: object;
  /**
   *
   * @type {string}
   * @memberof AuthnUserOut
   */
  email?: string;
  /**
   *
   * @type {boolean}
   * @memberof AuthnUserOut
   */
  email_verified?: boolean;
  /**
   *
   * @type {object}
   * @memberof AuthnUserOut
   */
  id?: object;
  /**
   *
   * @type {string}
   * @memberof AuthnUserOut
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof AuthnUserOut
   */
  role?: string;
  /**
   *
   * @type {object}
   * @memberof AuthnUserOut
   */
  updated_at?: object;
}

/**
 * Check if a given object implements the AuthnUserOut interface.
 */
export function instanceOfAuthnUserOut(value: object): value is AuthnUserOut {
  return true;
}

export function AuthnUserOutFromJSON(json: any): AuthnUserOut {
  return AuthnUserOutFromJSONTyped(json, false);
}

export function AuthnUserOutFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AuthnUserOut {
  if (json == null) {
    return json;
  }
  return {
    created_at: json["created_at"] == null ? undefined : json["created_at"],
    email: json["email"] == null ? undefined : json["email"],
    email_verified:
      json["email_verified"] == null ? undefined : json["email_verified"],
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    role: json["role"] == null ? undefined : json["role"],
    updated_at: json["updated_at"] == null ? undefined : json["updated_at"],
  };
}

export function AuthnUserOutToJSON(json: any): AuthnUserOut {
  return AuthnUserOutToJSONTyped(json, false);
}

export function AuthnUserOutToJSONTyped(
  value?: AuthnUserOut | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: value["created_at"],
    email: value["email"],
    email_verified: value["email_verified"],
    id: value["id"],
    name: value["name"],
    role: value["role"],
    updated_at: value["updated_at"],
  };
}
