/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DtoAnnotationResponse
 */
export interface DtoAnnotationResponse {
  /**
   *
   * @type {string}
   * @memberof DtoAnnotationResponse
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof DtoAnnotationResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof DtoAnnotationResponse
   */
  key?: string;
  /**
   *
   * @type {string}
   * @memberof DtoAnnotationResponse
   */
  organization_id?: string;
  /**
   *
   * @type {string}
   * @memberof DtoAnnotationResponse
   */
  updated_at?: string;
  /**
   *
   * @type {string}
   * @memberof DtoAnnotationResponse
   */
  value?: string;
}

/**
 * Check if a given object implements the DtoAnnotationResponse interface.
 */
export function instanceOfDtoAnnotationResponse(
  value: object,
): value is DtoAnnotationResponse {
  return true;
}

export function DtoAnnotationResponseFromJSON(
  json: any,
): DtoAnnotationResponse {
  return DtoAnnotationResponseFromJSONTyped(json, false);
}

export function DtoAnnotationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DtoAnnotationResponse {
  if (json == null) {
    return json;
  }
  return {
    created_at: json["created_at"] == null ? undefined : json["created_at"],
    id: json["id"] == null ? undefined : json["id"],
    key: json["key"] == null ? undefined : json["key"],
    organization_id:
      json["organization_id"] == null ? undefined : json["organization_id"],
    updated_at: json["updated_at"] == null ? undefined : json["updated_at"],
    value: json["value"] == null ? undefined : json["value"],
  };
}

export function DtoAnnotationResponseToJSON(json: any): DtoAnnotationResponse {
  return DtoAnnotationResponseToJSONTyped(json, false);
}

export function DtoAnnotationResponseToJSONTyped(
  value?: DtoAnnotationResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: value["created_at"],
    id: value["id"],
    key: value["key"],
    organization_id: value["organization_id"],
    updated_at: value["updated_at"],
    value: value["value"],
  };
}
