/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DtoCreateClusterRequest
 */
export interface DtoCreateClusterRequest {
  /**
   *
   * @type {string}
   * @memberof DtoCreateClusterRequest
   */
  cluster_provider?: string;
  /**
   *
   * @type {string}
   * @memberof DtoCreateClusterRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof DtoCreateClusterRequest
   */
  region?: string;
}

/**
 * Check if a given object implements the DtoCreateClusterRequest interface.
 */
export function instanceOfDtoCreateClusterRequest(
  value: object,
): value is DtoCreateClusterRequest {
  return true;
}

export function DtoCreateClusterRequestFromJSON(
  json: any,
): DtoCreateClusterRequest {
  return DtoCreateClusterRequestFromJSONTyped(json, false);
}

export function DtoCreateClusterRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DtoCreateClusterRequest {
  if (json == null) {
    return json;
  }
  return {
    cluster_provider:
      json["cluster_provider"] == null ? undefined : json["cluster_provider"],
    name: json["name"] == null ? undefined : json["name"],
    region: json["region"] == null ? undefined : json["region"],
  };
}

export function DtoCreateClusterRequestToJSON(
  json: any,
): DtoCreateClusterRequest {
  return DtoCreateClusterRequestToJSONTyped(json, false);
}

export function DtoCreateClusterRequestToJSONTyped(
  value?: DtoCreateClusterRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    cluster_provider: value["cluster_provider"],
    name: value["name"],
    region: value["region"],
  };
}
