/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DtoCreateTaintRequest
 */
export interface DtoCreateTaintRequest {
  /**
   *
   * @type {string}
   * @memberof DtoCreateTaintRequest
   */
  effect?: string;
  /**
   *
   * @type {string}
   * @memberof DtoCreateTaintRequest
   */
  key?: string;
  /**
   *
   * @type {string}
   * @memberof DtoCreateTaintRequest
   */
  value?: string;
}

/**
 * Check if a given object implements the DtoCreateTaintRequest interface.
 */
export function instanceOfDtoCreateTaintRequest(
  value: object,
): value is DtoCreateTaintRequest {
  return true;
}

export function DtoCreateTaintRequestFromJSON(
  json: any,
): DtoCreateTaintRequest {
  return DtoCreateTaintRequestFromJSONTyped(json, false);
}

export function DtoCreateTaintRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DtoCreateTaintRequest {
  if (json == null) {
    return json;
  }
  return {
    effect: json["effect"] == null ? undefined : json["effect"],
    key: json["key"] == null ? undefined : json["key"],
    value: json["value"] == null ? undefined : json["value"],
  };
}

export function DtoCreateTaintRequestToJSON(json: any): DtoCreateTaintRequest {
  return DtoCreateTaintRequestToJSONTyped(json, false);
}

export function DtoCreateTaintRequestToJSONTyped(
  value?: DtoCreateTaintRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    effect: value["effect"],
    key: value["key"],
    value: value["value"],
  };
}
