/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DtoRefreshRequest
 */
export interface DtoRefreshRequest {
  /**
   *
   * @type {string}
   * @memberof DtoRefreshRequest
   */
  refresh_token?: string;
}

/**
 * Check if a given object implements the DtoRefreshRequest interface.
 */
export function instanceOfDtoRefreshRequest(
  value: object,
): value is DtoRefreshRequest {
  return true;
}

export function DtoRefreshRequestFromJSON(json: any): DtoRefreshRequest {
  return DtoRefreshRequestFromJSONTyped(json, false);
}

export function DtoRefreshRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DtoRefreshRequest {
  if (json == null) {
    return json;
  }
  return {
    refresh_token:
      json["refresh_token"] == null ? undefined : json["refresh_token"],
  };
}

export function DtoRefreshRequestToJSON(json: any): DtoRefreshRequest {
  return DtoRefreshRequestToJSONTyped(json, false);
}

export function DtoRefreshRequestToJSONTyped(
  value?: DtoRefreshRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    refresh_token: value["refresh_token"],
  };
}
