/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DtoSshResponse
 */
export interface DtoSshResponse {
  /**
   *
   * @type {string}
   * @memberof DtoSshResponse
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof DtoSshResponse
   */
  fingerprint?: string;
  /**
   *
   * @type {string}
   * @memberof DtoSshResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof DtoSshResponse
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof DtoSshResponse
   */
  organization_id?: string;
  /**
   *
   * @type {string}
   * @memberof DtoSshResponse
   */
  public_key?: string;
  /**
   *
   * @type {string}
   * @memberof DtoSshResponse
   */
  updated_at?: string;
}

/**
 * Check if a given object implements the DtoSshResponse interface.
 */
export function instanceOfDtoSshResponse(
  value: object,
): value is DtoSshResponse {
  return true;
}

export function DtoSshResponseFromJSON(json: any): DtoSshResponse {
  return DtoSshResponseFromJSONTyped(json, false);
}

export function DtoSshResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DtoSshResponse {
  if (json == null) {
    return json;
  }
  return {
    created_at: json["created_at"] == null ? undefined : json["created_at"],
    fingerprint: json["fingerprint"] == null ? undefined : json["fingerprint"],
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    organization_id:
      json["organization_id"] == null ? undefined : json["organization_id"],
    public_key: json["public_key"] == null ? undefined : json["public_key"],
    updated_at: json["updated_at"] == null ? undefined : json["updated_at"],
  };
}

export function DtoSshResponseToJSON(json: any): DtoSshResponse {
  return DtoSshResponseToJSONTyped(json, false);
}

export function DtoSshResponseToJSONTyped(
  value?: DtoSshResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: value["created_at"],
    fingerprint: value["fingerprint"],
    id: value["id"],
    name: value["name"],
    organization_id: value["organization_id"],
    public_key: value["public_key"],
    updated_at: value["updated_at"],
  };
}
