/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DtoUpdateTaintRequest
 */
export interface DtoUpdateTaintRequest {
  /**
   *
   * @type {string}
   * @memberof DtoUpdateTaintRequest
   */
  effect?: string;
  /**
   *
   * @type {string}
   * @memberof DtoUpdateTaintRequest
   */
  key?: string;
  /**
   *
   * @type {string}
   * @memberof DtoUpdateTaintRequest
   */
  value?: string;
}

/**
 * Check if a given object implements the DtoUpdateTaintRequest interface.
 */
export function instanceOfDtoUpdateTaintRequest(
  value: object,
): value is DtoUpdateTaintRequest {
  return true;
}

export function DtoUpdateTaintRequestFromJSON(
  json: any,
): DtoUpdateTaintRequest {
  return DtoUpdateTaintRequestFromJSONTyped(json, false);
}

export function DtoUpdateTaintRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DtoUpdateTaintRequest {
  if (json == null) {
    return json;
  }
  return {
    effect: json["effect"] == null ? undefined : json["effect"],
    key: json["key"] == null ? undefined : json["key"],
    value: json["value"] == null ? undefined : json["value"],
  };
}

export function DtoUpdateTaintRequestToJSON(json: any): DtoUpdateTaintRequest {
  return DtoUpdateTaintRequestToJSONTyped(json, false);
}

export function DtoUpdateTaintRequestToJSONTyped(
  value?: DtoUpdateTaintRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    effect: value["effect"],
    key: value["key"],
    value: value["value"],
  };
}
