/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DtoUpdateDomainRequest
 */
export interface DtoUpdateDomainRequest {
  /**
   *
   * @type {string}
   * @memberof DtoUpdateDomainRequest
   */
  credential_id?: string;
  /**
   *
   * @type {string}
   * @memberof DtoUpdateDomainRequest
   */
  domain_name?: string;
  /**
   *
   * @type {string}
   * @memberof DtoUpdateDomainRequest
   */
  status?: DtoUpdateDomainRequestStatusEnum;
  /**
   *
   * @type {string}
   * @memberof DtoUpdateDomainRequest
   */
  zone_id?: string;
}

/**
 * @export
 */
export const DtoUpdateDomainRequestStatusEnum = {
  pending: "pending",
  provisioning: "provisioning",
  ready: "ready",
  failed: "failed",
} as const;
export type DtoUpdateDomainRequestStatusEnum =
  (typeof DtoUpdateDomainRequestStatusEnum)[keyof typeof DtoUpdateDomainRequestStatusEnum];

/**
 * Check if a given object implements the DtoUpdateDomainRequest interface.
 */
export function instanceOfDtoUpdateDomainRequest(
  value: object,
): value is DtoUpdateDomainRequest {
  return true;
}

export function DtoUpdateDomainRequestFromJSON(
  json: any,
): DtoUpdateDomainRequest {
  return DtoUpdateDomainRequestFromJSONTyped(json, false);
}

export function DtoUpdateDomainRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DtoUpdateDomainRequest {
  if (json == null) {
    return json;
  }
  return {
    credential_id:
      json["credential_id"] == null ? undefined : json["credential_id"],
    domain_name: json["domain_name"] == null ? undefined : json["domain_name"],
    status: json["status"] == null ? undefined : json["status"],
    zone_id: json["zone_id"] == null ? undefined : json["zone_id"],
  };
}

export function DtoUpdateDomainRequestToJSON(
  json: any,
): DtoUpdateDomainRequest {
  return DtoUpdateDomainRequestToJSONTyped(json, false);
}

export function DtoUpdateDomainRequestToJSONTyped(
  value?: DtoUpdateDomainRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    credential_id: value["credential_id"],
    domain_name: value["domain_name"],
    status: value["status"],
    zone_id: value["zone_id"],
  };
}
