/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DtoUpdateClusterRequest
 */
export interface DtoUpdateClusterRequest {
  /**
   *
   * @type {string}
   * @memberof DtoUpdateClusterRequest
   */
  cluster_provider?: string;
  /**
   *
   * @type {string}
   * @memberof DtoUpdateClusterRequest
   */
  docker_image?: string;
  /**
   *
   * @type {string}
   * @memberof DtoUpdateClusterRequest
   */
  docker_tag?: string;
  /**
   *
   * @type {string}
   * @memberof DtoUpdateClusterRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof DtoUpdateClusterRequest
   */
  region?: string;
}

/**
 * Check if a given object implements the DtoUpdateClusterRequest interface.
 */
export function instanceOfDtoUpdateClusterRequest(
  value: object,
): value is DtoUpdateClusterRequest {
  return true;
}

export function DtoUpdateClusterRequestFromJSON(
  json: any,
): DtoUpdateClusterRequest {
  return DtoUpdateClusterRequestFromJSONTyped(json, false);
}

export function DtoUpdateClusterRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DtoUpdateClusterRequest {
  if (json == null) {
    return json;
  }
  return {
    cluster_provider:
      json["cluster_provider"] == null ? undefined : json["cluster_provider"],
    docker_image:
      json["docker_image"] == null ? undefined : json["docker_image"],
    docker_tag: json["docker_tag"] == null ? undefined : json["docker_tag"],
    name: json["name"] == null ? undefined : json["name"],
    region: json["region"] == null ? undefined : json["region"],
  };
}

export function DtoUpdateClusterRequestToJSON(
  json: any,
): DtoUpdateClusterRequest {
  return DtoUpdateClusterRequestToJSONTyped(json, false);
}

export function DtoUpdateClusterRequestToJSONTyped(
  value?: DtoUpdateClusterRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    cluster_provider: value["cluster_provider"],
    docker_image: value["docker_image"],
    docker_tag: value["docker_tag"],
    name: value["name"],
    region: value["region"],
  };
}
