/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface HandlersMemberOut
 */
export interface HandlersMemberOut {
  /**
   *
   * @type {string}
   * @memberof HandlersMemberOut
   */
  email?: string;
  /**
   * owner/admin/member
   * @type {string}
   * @memberof HandlersMemberOut
   */
  role?: string;
  /**
   *
   * @type {string}
   * @memberof HandlersMemberOut
   */
  user_id?: string;
}

/**
 * Check if a given object implements the HandlersMemberOut interface.
 */
export function instanceOfHandlersMemberOut(
  value: object,
): value is HandlersMemberOut {
  return true;
}

export function HandlersMemberOutFromJSON(json: any): HandlersMemberOut {
  return HandlersMemberOutFromJSONTyped(json, false);
}

export function HandlersMemberOutFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HandlersMemberOut {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"] == null ? undefined : json["email"],
    role: json["role"] == null ? undefined : json["role"],
    user_id: json["user_id"] == null ? undefined : json["user_id"],
  };
}

export function HandlersMemberOutToJSON(json: any): HandlersMemberOut {
  return HandlersMemberOutToJSONTyped(json, false);
}

export function HandlersMemberOutToJSONTyped(
  value?: HandlersMemberOut | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
    role: value["role"],
    user_id: value["user_id"],
  };
}
