/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface JobsEnqueueResp
 */
export interface JobsEnqueueResp {
  /**
   *
   * @type {string}
   * @memberof JobsEnqueueResp
   */
  id?: string;
}

/**
 * Check if a given object implements the JobsEnqueueResp interface.
 */
export function instanceOfJobsEnqueueResp(
  value: object,
): value is JobsEnqueueResp {
  return true;
}

export function JobsEnqueueRespFromJSON(json: any): JobsEnqueueResp {
  return JobsEnqueueRespFromJSONTyped(json, false);
}

export function JobsEnqueueRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): JobsEnqueueResp {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
  };
}

export function JobsEnqueueRespToJSON(json: any): JobsEnqueueResp {
  return JobsEnqueueRespToJSONTyped(json, false);
}

export function JobsEnqueueRespToJSONTyped(
  value?: JobsEnqueueResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
  };
}
