/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LabelsNodePoolBrief
 */
export interface LabelsNodePoolBrief {
  /**
   *
   * @type {string}
   * @memberof LabelsNodePoolBrief
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof LabelsNodePoolBrief
   */
  name?: string;
}

/**
 * Check if a given object implements the LabelsNodePoolBrief interface.
 */
export function instanceOfLabelsNodePoolBrief(
  value: object,
): value is LabelsNodePoolBrief {
  return true;
}

export function LabelsNodePoolBriefFromJSON(json: any): LabelsNodePoolBrief {
  return LabelsNodePoolBriefFromJSONTyped(json, false);
}

export function LabelsNodePoolBriefFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LabelsNodePoolBrief {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function LabelsNodePoolBriefToJSON(json: any): LabelsNodePoolBrief {
  return LabelsNodePoolBriefToJSONTyped(json, false);
}

export function LabelsNodePoolBriefToJSONTyped(
  value?: LabelsNodePoolBrief | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
  };
}
