/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LabelsUpdateLabelRequest
 */
export interface LabelsUpdateLabelRequest {
  /**
   *
   * @type {string}
   * @memberof LabelsUpdateLabelRequest
   */
  key?: string;
  /**
   *
   * @type {string}
   * @memberof LabelsUpdateLabelRequest
   */
  value?: string;
}

/**
 * Check if a given object implements the LabelsUpdateLabelRequest interface.
 */
export function instanceOfLabelsUpdateLabelRequest(
  value: object,
): value is LabelsUpdateLabelRequest {
  return true;
}

export function LabelsUpdateLabelRequestFromJSON(
  json: any,
): LabelsUpdateLabelRequest {
  return LabelsUpdateLabelRequestFromJSONTyped(json, false);
}

export function LabelsUpdateLabelRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LabelsUpdateLabelRequest {
  if (json == null) {
    return json;
  }
  return {
    key: json["key"] == null ? undefined : json["key"],
    value: json["value"] == null ? undefined : json["value"],
  };
}

export function LabelsUpdateLabelRequestToJSON(
  json: any,
): LabelsUpdateLabelRequest {
  return LabelsUpdateLabelRequestToJSONTyped(json, false);
}

export function LabelsUpdateLabelRequestToJSONTyped(
  value?: LabelsUpdateLabelRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    key: value["key"],
    value: value["value"],
  };
}
