/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NodepoolsCreateNodePoolRequest
 */
export interface NodepoolsCreateNodePoolRequest {
  /**
   *
   * @type {string}
   * @memberof NodepoolsCreateNodePoolRequest
   */
  name?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof NodepoolsCreateNodePoolRequest
   */
  server_ids?: Array<string>;
}

/**
 * Check if a given object implements the NodepoolsCreateNodePoolRequest interface.
 */
export function instanceOfNodepoolsCreateNodePoolRequest(
  value: object,
): value is NodepoolsCreateNodePoolRequest {
  return true;
}

export function NodepoolsCreateNodePoolRequestFromJSON(
  json: any,
): NodepoolsCreateNodePoolRequest {
  return NodepoolsCreateNodePoolRequestFromJSONTyped(json, false);
}

export function NodepoolsCreateNodePoolRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NodepoolsCreateNodePoolRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    server_ids: json["server_ids"] == null ? undefined : json["server_ids"],
  };
}

export function NodepoolsCreateNodePoolRequestToJSON(
  json: any,
): NodepoolsCreateNodePoolRequest {
  return NodepoolsCreateNodePoolRequestToJSONTyped(json, false);
}

export function NodepoolsCreateNodePoolRequestToJSONTyped(
  value?: NodepoolsCreateNodePoolRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    server_ids: value["server_ids"],
  };
}
