/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ServersUpdateServerRequest
 */
export interface ServersUpdateServerRequest {
  /**
   *
   * @type {string}
   * @memberof ServersUpdateServerRequest
   */
  hostname?: string;
  /**
   *
   * @type {string}
   * @memberof ServersUpdateServerRequest
   */
  ip_address?: string;
  /**
   *
   * @type {string}
   * @memberof ServersUpdateServerRequest
   */
  role?: string;
  /**
   *
   * @type {string}
   * @memberof ServersUpdateServerRequest
   */
  ssh_key_id?: string;
  /**
   *
   * @type {string}
   * @memberof ServersUpdateServerRequest
   */
  ssh_user?: string;
  /**
   * enum: pending,provisioning,ready,failed
   * @type {string}
   * @memberof ServersUpdateServerRequest
   */
  status?: string;
}

/**
 * Check if a given object implements the ServersUpdateServerRequest interface.
 */
export function instanceOfServersUpdateServerRequest(
  value: object,
): value is ServersUpdateServerRequest {
  return true;
}

export function ServersUpdateServerRequestFromJSON(
  json: any,
): ServersUpdateServerRequest {
  return ServersUpdateServerRequestFromJSONTyped(json, false);
}

export function ServersUpdateServerRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ServersUpdateServerRequest {
  if (json == null) {
    return json;
  }
  return {
    hostname: json["hostname"] == null ? undefined : json["hostname"],
    ip_address: json["ip_address"] == null ? undefined : json["ip_address"],
    role: json["role"] == null ? undefined : json["role"],
    ssh_key_id: json["ssh_key_id"] == null ? undefined : json["ssh_key_id"],
    ssh_user: json["ssh_user"] == null ? undefined : json["ssh_user"],
    status: json["status"] == null ? undefined : json["status"],
  };
}

export function ServersUpdateServerRequestToJSON(
  json: any,
): ServersUpdateServerRequest {
  return ServersUpdateServerRequestToJSONTyped(json, false);
}

export function ServersUpdateServerRequestToJSONTyped(
  value?: ServersUpdateServerRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    hostname: value["hostname"],
    ip_address: value["ip_address"],
    role: value["role"],
    ssh_key_id: value["ssh_key_id"],
    ssh_user: value["ssh_user"],
    status: value["status"],
  };
}
