/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ServersServerResponse
 */
export interface ServersServerResponse {
  /**
   *
   * @type {string}
   * @memberof ServersServerResponse
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof ServersServerResponse
   */
  hostname?: string;
  /**
   *
   * @type {string}
   * @memberof ServersServerResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ServersServerResponse
   */
  ip_address?: string;
  /**
   *
   * @type {string}
   * @memberof ServersServerResponse
   */
  organization_id?: string;
  /**
   *
   * @type {string}
   * @memberof ServersServerResponse
   */
  role?: string;
  /**
   *
   * @type {string}
   * @memberof ServersServerResponse
   */
  ssh_key_id?: string;
  /**
   *
   * @type {string}
   * @memberof ServersServerResponse
   */
  ssh_user?: string;
  /**
   *
   * @type {string}
   * @memberof ServersServerResponse
   */
  status?: string;
  /**
   *
   * @type {string}
   * @memberof ServersServerResponse
   */
  updated_at?: string;
}

/**
 * Check if a given object implements the ServersServerResponse interface.
 */
export function instanceOfServersServerResponse(
  value: object,
): value is ServersServerResponse {
  return true;
}

export function ServersServerResponseFromJSON(
  json: any,
): ServersServerResponse {
  return ServersServerResponseFromJSONTyped(json, false);
}

export function ServersServerResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ServersServerResponse {
  if (json == null) {
    return json;
  }
  return {
    created_at: json["created_at"] == null ? undefined : json["created_at"],
    hostname: json["hostname"] == null ? undefined : json["hostname"],
    id: json["id"] == null ? undefined : json["id"],
    ip_address: json["ip_address"] == null ? undefined : json["ip_address"],
    organization_id:
      json["organization_id"] == null ? undefined : json["organization_id"],
    role: json["role"] == null ? undefined : json["role"],
    ssh_key_id: json["ssh_key_id"] == null ? undefined : json["ssh_key_id"],
    ssh_user: json["ssh_user"] == null ? undefined : json["ssh_user"],
    status: json["status"] == null ? undefined : json["status"],
    updated_at: json["updated_at"] == null ? undefined : json["updated_at"],
  };
}

export function ServersServerResponseToJSON(json: any): ServersServerResponse {
  return ServersServerResponseToJSONTyped(json, false);
}

export function ServersServerResponseToJSONTyped(
  value?: ServersServerResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: value["created_at"],
    hostname: value["hostname"],
    id: value["id"],
    ip_address: value["ip_address"],
    organization_id: value["organization_id"],
    role: value["role"],
    ssh_key_id: value["ssh_key_id"],
    ssh_user: value["ssh_user"],
    status: value["status"],
    updated_at: value["updated_at"],
  };
}
