/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TaintsCreateTaintRequest
 */
export interface TaintsCreateTaintRequest {
  /**
   *
   * @type {string}
   * @memberof TaintsCreateTaintRequest
   */
  effect?: string;
  /**
   *
   * @type {string}
   * @memberof TaintsCreateTaintRequest
   */
  key?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof TaintsCreateTaintRequest
   */
  node_pool_ids?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof TaintsCreateTaintRequest
   */
  value?: string;
}

/**
 * Check if a given object implements the TaintsCreateTaintRequest interface.
 */
export function instanceOfTaintsCreateTaintRequest(
  value: object,
): value is TaintsCreateTaintRequest {
  return true;
}

export function TaintsCreateTaintRequestFromJSON(
  json: any,
): TaintsCreateTaintRequest {
  return TaintsCreateTaintRequestFromJSONTyped(json, false);
}

export function TaintsCreateTaintRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TaintsCreateTaintRequest {
  if (json == null) {
    return json;
  }
  return {
    effect: json["effect"] == null ? undefined : json["effect"],
    key: json["key"] == null ? undefined : json["key"],
    node_pool_ids:
      json["node_pool_ids"] == null ? undefined : json["node_pool_ids"],
    value: json["value"] == null ? undefined : json["value"],
  };
}

export function TaintsCreateTaintRequestToJSON(
  json: any,
): TaintsCreateTaintRequest {
  return TaintsCreateTaintRequestToJSONTyped(json, false);
}

export function TaintsCreateTaintRequestToJSONTyped(
  value?: TaintsCreateTaintRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    effect: value["effect"],
    key: value["key"],
    node_pool_ids: value["node_pool_ids"],
    value: value["value"],
  };
}
