/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnnotationsAddAnnotationToNodePool
 */
export interface AnnotationsAddAnnotationToNodePool {
    /**
     * 
     * @type {Array<string>}
     * @memberof AnnotationsAddAnnotationToNodePool
     */
    node_pool_ids?: Array<string>;
}

/**
 * Check if a given object implements the AnnotationsAddAnnotationToNodePool interface.
 */
export function instanceOfAnnotationsAddAnnotationToNodePool(value: object): value is AnnotationsAddAnnotationToNodePool {
    return true;
}

export function AnnotationsAddAnnotationToNodePoolFromJSON(json: any): AnnotationsAddAnnotationToNodePool {
    return AnnotationsAddAnnotationToNodePoolFromJSONTyped(json, false);
}

export function AnnotationsAddAnnotationToNodePoolFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnotationsAddAnnotationToNodePool {
    if (json == null) {
        return json;
    }
    return {
        
        'node_pool_ids': json['node_pool_ids'] == null ? undefined : json['node_pool_ids'],
    };
}

export function AnnotationsAddAnnotationToNodePoolToJSON(json: any): AnnotationsAddAnnotationToNodePool {
    return AnnotationsAddAnnotationToNodePoolToJSONTyped(json, false);
}

export function AnnotationsAddAnnotationToNodePoolToJSONTyped(value?: AnnotationsAddAnnotationToNodePool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'node_pool_ids': value['node_pool_ids'],
    };
}

