/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthnLoginInput
 */
export interface AuthnLoginInput {
    /**
     * 
     * @type {string}
     * @memberof AuthnLoginInput
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthnLoginInput
     */
    password?: string;
}

/**
 * Check if a given object implements the AuthnLoginInput interface.
 */
export function instanceOfAuthnLoginInput(value: object): value is AuthnLoginInput {
    return true;
}

export function AuthnLoginInputFromJSON(json: any): AuthnLoginInput {
    return AuthnLoginInputFromJSONTyped(json, false);
}

export function AuthnLoginInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthnLoginInput {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function AuthnLoginInputToJSON(json: any): AuthnLoginInput {
    return AuthnLoginInputToJSONTyped(json, false);
}

export function AuthnLoginInputToJSONTyped(value?: AuthnLoginInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

