/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClustersLabelBrief
 */
export interface ClustersLabelBrief {
    /**
     * 
     * @type {string}
     * @memberof ClustersLabelBrief
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClustersLabelBrief
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof ClustersLabelBrief
     */
    value?: string;
}

/**
 * Check if a given object implements the ClustersLabelBrief interface.
 */
export function instanceOfClustersLabelBrief(value: object): value is ClustersLabelBrief {
    return true;
}

export function ClustersLabelBriefFromJSON(json: any): ClustersLabelBrief {
    return ClustersLabelBriefFromJSONTyped(json, false);
}

export function ClustersLabelBriefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClustersLabelBrief {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function ClustersLabelBriefToJSON(json: any): ClustersLabelBrief {
    return ClustersLabelBriefToJSONTyped(json, false);
}

export function ClustersLabelBriefToJSONTyped(value?: ClustersLabelBrief | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'value': value['value'],
    };
}

