/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodepoolsAttachAnnotationsRequest
 */
export interface NodepoolsAttachAnnotationsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof NodepoolsAttachAnnotationsRequest
     */
    annotation_ids?: Array<string>;
}

/**
 * Check if a given object implements the NodepoolsAttachAnnotationsRequest interface.
 */
export function instanceOfNodepoolsAttachAnnotationsRequest(value: object): value is NodepoolsAttachAnnotationsRequest {
    return true;
}

export function NodepoolsAttachAnnotationsRequestFromJSON(json: any): NodepoolsAttachAnnotationsRequest {
    return NodepoolsAttachAnnotationsRequestFromJSONTyped(json, false);
}

export function NodepoolsAttachAnnotationsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodepoolsAttachAnnotationsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'annotation_ids': json['annotation_ids'] == null ? undefined : json['annotation_ids'],
    };
}

export function NodepoolsAttachAnnotationsRequestToJSON(json: any): NodepoolsAttachAnnotationsRequest {
    return NodepoolsAttachAnnotationsRequestToJSONTyped(json, false);
}

export function NodepoolsAttachAnnotationsRequestToJSONTyped(value?: NodepoolsAttachAnnotationsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'annotation_ids': value['annotation_ids'],
    };
}

