/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgsInviteInput
 */
export interface OrgsInviteInput {
    /**
     * 
     * @type {string}
     * @memberof OrgsInviteInput
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof OrgsInviteInput
     */
    role?: string;
}

/**
 * Check if a given object implements the OrgsInviteInput interface.
 */
export function instanceOfOrgsInviteInput(value: object): value is OrgsInviteInput {
    return true;
}

export function OrgsInviteInputFromJSON(json: any): OrgsInviteInput {
    return OrgsInviteInputFromJSONTyped(json, false);
}

export function OrgsInviteInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgsInviteInput {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function OrgsInviteInputToJSON(json: any): OrgsInviteInput {
    return OrgsInviteInputToJSONTyped(json, false);
}

export function OrgsInviteInputToJSONTyped(value?: OrgsInviteInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'role': value['role'],
    };
}

