/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaintsAddTaintToPoolRequest
 */
export interface TaintsAddTaintToPoolRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof TaintsAddTaintToPoolRequest
     */
    node_pool_ids?: Array<string>;
}

/**
 * Check if a given object implements the TaintsAddTaintToPoolRequest interface.
 */
export function instanceOfTaintsAddTaintToPoolRequest(value: object): value is TaintsAddTaintToPoolRequest {
    return true;
}

export function TaintsAddTaintToPoolRequestFromJSON(json: any): TaintsAddTaintToPoolRequest {
    return TaintsAddTaintToPoolRequestFromJSONTyped(json, false);
}

export function TaintsAddTaintToPoolRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaintsAddTaintToPoolRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'node_pool_ids': json['node_pool_ids'] == null ? undefined : json['node_pool_ids'],
    };
}

export function TaintsAddTaintToPoolRequestToJSON(json: any): TaintsAddTaintToPoolRequest {
    return TaintsAddTaintToPoolRequestToJSONTyped(json, false);
}

export function TaintsAddTaintToPoolRequestToJSONTyped(value?: TaintsAddTaintToPoolRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'node_pool_ids': value['node_pool_ids'],
    };
}

