/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface DtoAttachLabelsRequest
 */
export interface DtoAttachLabelsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof DtoAttachLabelsRequest
     */
    label_ids?: Array<string>;
}

/**
 * Check if a given object implements the DtoAttachLabelsRequest interface.
 */
export function instanceOfDtoAttachLabelsRequest(value: object): value is DtoAttachLabelsRequest {
    return true;
}

export function DtoAttachLabelsRequestFromJSON(json: any): DtoAttachLabelsRequest {
    return DtoAttachLabelsRequestFromJSONTyped(json, false);
}

export function DtoAttachLabelsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoAttachLabelsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'label_ids': json['label_ids'] == null ? undefined : json['label_ids'],
    };
}

export function DtoAttachLabelsRequestToJSON(json: any): DtoAttachLabelsRequest {
    return DtoAttachLabelsRequestToJSONTyped(json, false);
}

export function DtoAttachLabelsRequestToJSONTyped(value?: DtoAttachLabelsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label_ids': value['label_ids'],
    };
}

