/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface DtoAttachTaintsRequest
 */
export interface DtoAttachTaintsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof DtoAttachTaintsRequest
     */
    taint_ids?: Array<string>;
}

/**
 * Check if a given object implements the DtoAttachTaintsRequest interface.
 */
export function instanceOfDtoAttachTaintsRequest(value: object): value is DtoAttachTaintsRequest {
    return true;
}

export function DtoAttachTaintsRequestFromJSON(json: any): DtoAttachTaintsRequest {
    return DtoAttachTaintsRequestFromJSONTyped(json, false);
}

export function DtoAttachTaintsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoAttachTaintsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'taint_ids': json['taint_ids'] == null ? undefined : json['taint_ids'],
    };
}

export function DtoAttachTaintsRequestToJSON(json: any): DtoAttachTaintsRequest {
    return DtoAttachTaintsRequestToJSONTyped(json, false);
}

export function DtoAttachTaintsRequestToJSONTyped(value?: DtoAttachTaintsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taint_ids': value['taint_ids'],
    };
}

