/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface DtoAuthStartResponse
 */
export interface DtoAuthStartResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoAuthStartResponse
     */
    auth_url?: string;
}

/**
 * Check if a given object implements the DtoAuthStartResponse interface.
 */
export function instanceOfDtoAuthStartResponse(value: object): value is DtoAuthStartResponse {
    return true;
}

export function DtoAuthStartResponseFromJSON(json: any): DtoAuthStartResponse {
    return DtoAuthStartResponseFromJSONTyped(json, false);
}

export function DtoAuthStartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoAuthStartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'auth_url': json['auth_url'] == null ? undefined : json['auth_url'],
    };
}

export function DtoAuthStartResponseToJSON(json: any): DtoAuthStartResponse {
    return DtoAuthStartResponseToJSONTyped(json, false);
}

export function DtoAuthStartResponseToJSONTyped(value?: DtoAuthStartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth_url': value['auth_url'],
    };
}

