/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface DtoCreateClusterRequest
 */
export interface DtoCreateClusterRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoCreateClusterRequest
     */
    captain_domain?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateClusterRequest
     */
    cluster_load_balancer?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateClusterRequest
     */
    control_load_balancer?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateClusterRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateClusterRequest
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateClusterRequest
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateClusterRequest
     */
    status?: string;
}

/**
 * Check if a given object implements the DtoCreateClusterRequest interface.
 */
export function instanceOfDtoCreateClusterRequest(value: object): value is DtoCreateClusterRequest {
    return true;
}

export function DtoCreateClusterRequestFromJSON(json: any): DtoCreateClusterRequest {
    return DtoCreateClusterRequestFromJSONTyped(json, false);
}

export function DtoCreateClusterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoCreateClusterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'captain_domain': json['captain_domain'] == null ? undefined : json['captain_domain'],
        'cluster_load_balancer': json['cluster_load_balancer'] == null ? undefined : json['cluster_load_balancer'],
        'control_load_balancer': json['control_load_balancer'] == null ? undefined : json['control_load_balancer'],
        'name': json['name'] == null ? undefined : json['name'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'region': json['region'] == null ? undefined : json['region'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function DtoCreateClusterRequestToJSON(json: any): DtoCreateClusterRequest {
    return DtoCreateClusterRequestToJSONTyped(json, false);
}

export function DtoCreateClusterRequestToJSONTyped(value?: DtoCreateClusterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'captain_domain': value['captain_domain'],
        'cluster_load_balancer': value['cluster_load_balancer'],
        'control_load_balancer': value['control_load_balancer'],
        'name': value['name'],
        'provider': value['provider'],
        'region': value['region'],
        'status': value['status'],
    };
}

