/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DtoNodePoolResponse } from "./DtoNodePoolResponse"
import { DtoNodePoolResponseFromJSON, DtoNodePoolResponseToJSON, } from "./DtoNodePoolResponse"
import type { DtoServerResponse } from "./DtoServerResponse"
import { DtoServerResponseFromJSON, DtoServerResponseToJSON, } from "./DtoServerResponse"

/**
 * 
 * @export
 * @interface DtoClusterResponse
 */
export interface DtoClusterResponse {
    /**
     * 
     * @type {DtoServerResponse}
     * @memberof DtoClusterResponse
     */
    bastion_server?: DtoServerResponse;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    captain_domain?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    certificate_key?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    cluster_load_balancer?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    control_load_balancer?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    name?: string;
    /**
     * 
     * @type {Array<DtoNodePoolResponse>}
     * @memberof DtoClusterResponse
     */
    node_pools?: Array<DtoNodePoolResponse>;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    random_token?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoClusterResponse
     */
    updated_at?: string;
}

/**
 * Check if a given object implements the DtoClusterResponse interface.
 */
export function instanceOfDtoClusterResponse(value: object): value is DtoClusterResponse {
    return true;
}

export function DtoClusterResponseFromJSON(json: any): DtoClusterResponse {
    return DtoClusterResponseFromJSONTyped(json, false);
}

export function DtoClusterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoClusterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bastion_server': json['bastion_server'] == null ? undefined : DtoServerResponseFromJSON(json['bastion_server']),
        'captain_domain': json['captain_domain'] == null ? undefined : json['captain_domain'],
        'certificate_key': json['certificate_key'] == null ? undefined : json['certificate_key'],
        'cluster_load_balancer': json['cluster_load_balancer'] == null ? undefined : json['cluster_load_balancer'],
        'control_load_balancer': json['control_load_balancer'] == null ? undefined : json['control_load_balancer'],
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'node_pools': json['node_pools'] == null ? undefined : ((json['node_pools'] as Array<any>).map(DtoNodePoolResponseFromJSON)),
        'provider': json['provider'] == null ? undefined : json['provider'],
        'random_token': json['random_token'] == null ? undefined : json['random_token'],
        'region': json['region'] == null ? undefined : json['region'],
        'status': json['status'] == null ? undefined : json['status'],
        'updated_at': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function DtoClusterResponseToJSON(json: any): DtoClusterResponse {
    return DtoClusterResponseToJSONTyped(json, false);
}

export function DtoClusterResponseToJSONTyped(value?: DtoClusterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bastion_server': DtoServerResponseToJSON(value['bastion_server']),
        'captain_domain': value['captain_domain'],
        'certificate_key': value['certificate_key'],
        'cluster_load_balancer': value['cluster_load_balancer'],
        'control_load_balancer': value['control_load_balancer'],
        'created_at': value['created_at'],
        'id': value['id'],
        'name': value['name'],
        'node_pools': value['node_pools'] == null ? undefined : ((value['node_pools'] as Array<any>).map(DtoNodePoolResponseToJSON)),
        'provider': value['provider'],
        'random_token': value['random_token'],
        'region': value['region'],
        'status': value['status'],
        'updated_at': value['updated_at'],
    };
}

