/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface DtoUpdateLabelRequest
 */
export interface DtoUpdateLabelRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateLabelRequest
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoUpdateLabelRequest
     */
    value?: string;
}

/**
 * Check if a given object implements the DtoUpdateLabelRequest interface.
 */
export function instanceOfDtoUpdateLabelRequest(value: object): value is DtoUpdateLabelRequest {
    return true;
}

export function DtoUpdateLabelRequestFromJSON(json: any): DtoUpdateLabelRequest {
    return DtoUpdateLabelRequestFromJSONTyped(json, false);
}

export function DtoUpdateLabelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoUpdateLabelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function DtoUpdateLabelRequestToJSON(json: any): DtoUpdateLabelRequest {
    return DtoUpdateLabelRequestToJSONTyped(json, false);
}

export function DtoUpdateLabelRequestToJSONTyped(value?: DtoUpdateLabelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

