/* tslint:disable */
/* eslint-disable */
/**
 * AutoGlue API
 * API for managing K3s clusters across cloud providers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface HandlersOrgCreateReq
 */
export interface HandlersOrgCreateReq {
    /**
     * 
     * @type {string}
     * @memberof HandlersOrgCreateReq
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersOrgCreateReq
     */
    name?: string;
}

/**
 * Check if a given object implements the HandlersOrgCreateReq interface.
 */
export function instanceOfHandlersOrgCreateReq(value: object): value is HandlersOrgCreateReq {
    return true;
}

export function HandlersOrgCreateReqFromJSON(json: any): HandlersOrgCreateReq {
    return HandlersOrgCreateReqFromJSONTyped(json, false);
}

export function HandlersOrgCreateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersOrgCreateReq {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'] == null ? undefined : json['domain'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function HandlersOrgCreateReqToJSON(json: any): HandlersOrgCreateReq {
    return HandlersOrgCreateReqToJSONTyped(json, false);
}

export function HandlersOrgCreateReqToJSONTyped(value?: HandlersOrgCreateReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'name': value['name'],
    };
}

